"""
Script para poblar la base de datos con palabras iniciales para el juego del impostor.
Ejecutar: python populate_words.py
"""
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
import os
from dotenv import load_dotenv
import uuid

# Cargar variables de entorno
load_dotenv()

# Palabras iniciales con sus pistas (solo una palabra como pista)
INITIAL_WORDS = [
    # Comida (30 palabras)
    {"word": "PIZZA", "hint": "Italiana", "category": "Comida", "difficulty": "easy"},
    {"word": "HAMBURGUESA", "hint": "Rápida", "category": "Comida", "difficulty": "easy"},
    {"word": "SUSHI", "hint": "Japonesa", "category": "Comida", "difficulty": "medium"},
    {"word": "TACO", "hint": "Mexicana", "category": "Comida", "difficulty": "easy"},
    {"word": "PASTA", "hint": "Espagueti", "category": "Comida", "difficulty": "easy"},
    {"word": "HELADO", "hint": "Frío", "category": "Comida", "difficulty": "easy"},
    {"word": "CHOCOLATE", "hint": "Cacao", "category": "Comida", "difficulty": "easy"},
    {"word": "PAELLA", "hint": "Española", "category": "Comida", "difficulty": "medium"},
    {"word": "EMPANADA", "hint": "Rellena", "category": "Comida", "difficulty": "easy"},
    {"word": "SANDWICH", "hint": "Pan", "category": "Comida", "difficulty": "easy"},
    {"word": "ENSALADA", "hint": "Verde", "category": "Comida", "difficulty": "easy"},
    {"word": "AREPA", "hint": "Venezolana", "category": "Comida", "difficulty": "medium"},
    {"word": "CEVICHE", "hint": "Marino", "category": "Comida", "difficulty": "medium"},
    {"word": "BURRITO", "hint": "Enrollado", "category": "Comida", "difficulty": "easy"},
    {"word": "LASAÑA", "hint": "Capas", "category": "Comida", "difficulty": "medium"},
    {"word": "CROISSANT", "hint": "Francés", "category": "Comida", "difficulty": "medium"},
    {"word": "DONUT", "hint": "Glaseado", "category": "Comida", "difficulty": "easy"},
    {"word": "WAFFLE", "hint": "Cuadrado", "category": "Comida", "difficulty": "easy"},
    {"word": "PANQUEQUE", "hint": "Desayuno", "category": "Comida", "difficulty": "easy"},
    {"word": "GALLETA", "hint": "Crujiente", "category": "Comida", "difficulty": "easy"},
    {"word": "YOGURT", "hint": "Lácteo", "category": "Comida", "difficulty": "easy"},
    {"word": "CEREAL", "hint": "Caja", "category": "Comida", "difficulty": "easy"},
    {"word": "QUESO", "hint": "Lácteo", "category": "Comida", "difficulty": "easy"},
    {"word": "JAMÓN", "hint": "Cerdo", "category": "Comida", "difficulty": "easy"},
    {"word": "SALCHICHA", "hint": "Embutido", "category": "Comida", "difficulty": "easy"},
    {"word": "POLLO", "hint": "Ave", "category": "Comida", "difficulty": "easy"},
    {"word": "CARNE", "hint": "Res", "category": "Comida", "difficulty": "easy"},
    {"word": "PESCADO", "hint": "Marino", "category": "Comida", "difficulty": "easy"},
    {"word": "HUEVO", "hint": "Gallina", "category": "Comida", "difficulty": "easy"},
    {"word": "TORTILLA", "hint": "Maíz", "category": "Comida", "difficulty": "easy"},
    
    # Animales (35 palabras)
    {"word": "PERRO", "hint": "Leal", "category": "Animales", "difficulty": "easy"},
    {"word": "GATO", "hint": "Felino", "category": "Animales", "difficulty": "easy"},
    {"word": "ELEFANTE", "hint": "Trompa", "category": "Animales", "difficulty": "easy"},
    {"word": "LEÓN", "hint": "Melena", "category": "Animales", "difficulty": "easy"},
    {"word": "DELFÍN", "hint": "Marino", "category": "Animales", "difficulty": "medium"},
    {"word": "PINGÜINO", "hint": "Antártida", "category": "Animales", "difficulty": "easy"},
    {"word": "MARIPOSA", "hint": "Alas", "category": "Animales", "difficulty": "easy"},
    {"word": "COCODRILO", "hint": "Reptil", "category": "Animales", "difficulty": "medium"},
    {"word": "JIRAFA", "hint": "Cuello", "category": "Animales", "difficulty": "easy"},
    {"word": "CEBRA", "hint": "Rayas", "category": "Animales", "difficulty": "easy"},
    {"word": "TIGRE", "hint": "Felino", "category": "Animales", "difficulty": "easy"},
    {"word": "OSO", "hint": "Peludo", "category": "Animales", "difficulty": "easy"},
    {"word": "MONO", "hint": "Banano", "category": "Animales", "difficulty": "easy"},
    {"word": "SERPIENTE", "hint": "Venenosa", "category": "Animales", "difficulty": "medium"},
    {"word": "BALLENA", "hint": "Grande", "category": "Animales", "difficulty": "medium"},
    {"word": "TIBURÓN", "hint": "Dientes", "category": "Animales", "difficulty": "medium"},
    {"word": "ÁGUILA", "hint": "Vuelo", "category": "Animales", "difficulty": "medium"},
    {"word": "BÚHO", "hint": "Nocturno", "category": "Animales", "difficulty": "medium"},
    {"word": "PATO", "hint": "Cuac", "category": "Animales", "difficulty": "easy"},
    {"word": "GALLINA", "hint": "Huevos", "category": "Animales", "difficulty": "easy"},
    {"word": "CONEJO", "hint": "Zanahoria", "category": "Animales", "difficulty": "easy"},
    {"word": "RATÓN", "hint": "Pequeño", "category": "Animales", "difficulty": "easy"},
    {"word": "CABALLO", "hint": "Carrera", "category": "Animales", "difficulty": "easy"},
    {"word": "VACA", "hint": "Leche", "category": "Animales", "difficulty": "easy"},
    {"word": "OVEJA", "hint": "Lana", "category": "Animales", "difficulty": "easy"},
    {"word": "CERDO", "hint": "Granja", "category": "Animales", "difficulty": "easy"},
    {"word": "TORTUGA", "hint": "Caparazón", "category": "Animales", "difficulty": "easy"},
    {"word": "RANA", "hint": "Salto", "category": "Animales", "difficulty": "easy"},
    {"word": "ABEJA", "hint": "Miel", "category": "Animales", "difficulty": "easy"},
    {"word": "HORMIGA", "hint": "Trabajo", "category": "Animales", "difficulty": "easy"},
    {"word": "ARAÑA", "hint": "Telaraña", "category": "Animales", "difficulty": "medium"},
    {"word": "MOSCA", "hint": "Zumbido", "category": "Animales", "difficulty": "easy"},
    {"word": "MOSQUITO", "hint": "Picadura", "category": "Animales", "difficulty": "easy"},
    {"word": "CANGREJO", "hint": "Pinzas", "category": "Animales", "difficulty": "medium"},
    {"word": "PULPO", "hint": "Tentáculos", "category": "Animales", "difficulty": "medium"},
    
    # Lugares (30 palabras)
    {"word": "PLAYA", "hint": "Arena", "category": "Lugares", "difficulty": "easy"},
    {"word": "MONTAÑA", "hint": "Altura", "category": "Lugares", "difficulty": "easy"},
    {"word": "HOSPITAL", "hint": "Médico", "category": "Lugares", "difficulty": "easy"},
    {"word": "ESCUELA", "hint": "Estudio", "category": "Lugares", "difficulty": "easy"},
    {"word": "MUSEO", "hint": "Arte", "category": "Lugares", "difficulty": "medium"},
    {"word": "BIBLIOTECA", "hint": "Libros", "category": "Lugares", "difficulty": "easy"},
    {"word": "AEROPUERTO", "hint": "Aviones", "category": "Lugares", "difficulty": "medium"},
    {"word": "PARQUE", "hint": "Verde", "category": "Lugares", "difficulty": "easy"},
    {"word": "CINE", "hint": "Películas", "category": "Lugares", "difficulty": "easy"},
    {"word": "RESTAURANTE", "hint": "Comida", "category": "Lugares", "difficulty": "easy"},
    {"word": "SUPERMERCADO", "hint": "Compras", "category": "Lugares", "difficulty": "easy"},
    {"word": "FARMACIA", "hint": "Medicinas", "category": "Lugares", "difficulty": "easy"},
    {"word": "BANCO", "hint": "Dinero", "category": "Lugares", "difficulty": "easy"},
    {"word": "IGLESIA", "hint": "Religión", "category": "Lugares", "difficulty": "easy"},
    {"word": "ESTADIO", "hint": "Deportes", "category": "Lugares", "difficulty": "easy"},
    {"word": "TEATRO", "hint": "Actuación", "category": "Lugares", "difficulty": "medium"},
    {"word": "CIRCO", "hint": "Payasos", "category": "Lugares", "difficulty": "easy"},
    {"word": "ZOO", "hint": "Animales", "category": "Lugares", "difficulty": "easy"},
    {"word": "ACUARIO", "hint": "Peces", "category": "Lugares", "difficulty": "medium"},
    {"word": "HOTEL", "hint": "Hospedaje", "category": "Lugares", "difficulty": "easy"},
    {"word": "CASTILLO", "hint": "Medieval", "category": "Lugares", "difficulty": "medium"},
    {"word": "PIRÁMIDE", "hint": "Egipto", "category": "Lugares", "difficulty": "medium"},
    {"word": "PUENTE", "hint": "Conexión", "category": "Lugares", "difficulty": "easy"},
    {"word": "TÚNEL", "hint": "Subterráneo", "category": "Lugares", "difficulty": "medium"},
    {"word": "FARO", "hint": "Luz", "category": "Lugares", "difficulty": "medium"},
    {"word": "PUERTO", "hint": "Barcos", "category": "Lugares", "difficulty": "medium"},
    {"word": "ESTACIÓN", "hint": "Tren", "category": "Lugares", "difficulty": "easy"},
    {"word": "MERCADO", "hint": "Vendedores", "category": "Lugares", "difficulty": "easy"},
    {"word": "PLAZA", "hint": "Centro", "category": "Lugares", "difficulty": "easy"},
    {"word": "CUEVA", "hint": "Oscura", "category": "Lugares", "difficulty": "medium"},
    
    # Objetos (35 palabras)
    {"word": "TELÉFONO", "hint": "Llamada", "category": "Objetos", "difficulty": "easy"},
    {"word": "COMPUTADORA", "hint": "Digital", "category": "Objetos", "difficulty": "easy"},
    {"word": "GUITARRA", "hint": "Cuerdas", "category": "Objetos", "difficulty": "easy"},
    {"word": "PELOTA", "hint": "Redonda", "category": "Objetos", "difficulty": "easy"},
    {"word": "LIBRO", "hint": "Páginas", "category": "Objetos", "difficulty": "easy"},
    {"word": "RELOJ", "hint": "Tiempo", "category": "Objetos", "difficulty": "easy"},
    {"word": "CÁMARA", "hint": "Foto", "category": "Objetos", "difficulty": "easy"},
    {"word": "PARAGUAS", "hint": "Lluvia", "category": "Objetos", "difficulty": "easy"},
    {"word": "LÁPIZ", "hint": "Escribir", "category": "Objetos", "difficulty": "easy"},
    {"word": "BORRADOR", "hint": "Goma", "category": "Objetos", "difficulty": "easy"},
    {"word": "TIJERA", "hint": "Cortar", "category": "Objetos", "difficulty": "easy"},
    {"word": "ESPEJO", "hint": "Reflejo", "category": "Objetos", "difficulty": "easy"},
    {"word": "VELA", "hint": "Fuego", "category": "Objetos", "difficulty": "easy"},
    {"word": "LINTERNA", "hint": "Luz", "category": "Objetos", "difficulty": "easy"},
    {"word": "LLAVE", "hint": "Puerta", "category": "Objetos", "difficulty": "easy"},
    {"word": "MARTILLO", "hint": "Clavo", "category": "Objetos", "difficulty": "easy"},
    {"word": "DESTORNILLADOR", "hint": "Tornillo", "category": "Objetos", "difficulty": "medium"},
    {"word": "PINCEL", "hint": "Pintura", "category": "Objetos", "difficulty": "easy"},
    {"word": "CEPILLO", "hint": "Dientes", "category": "Objetos", "difficulty": "easy"},
    {"word": "PEINE", "hint": "Cabello", "category": "Objetos", "difficulty": "easy"},
    {"word": "TOALLA", "hint": "Seco", "category": "Objetos", "difficulty": "easy"},
    {"word": "JABÓN", "hint": "Limpio", "category": "Objetos", "difficulty": "easy"},
    {"word": "CHAMPÚ", "hint": "Lavado", "category": "Objetos", "difficulty": "easy"},
    {"word": "BOTELLA", "hint": "Líquido", "category": "Objetos", "difficulty": "easy"},
    {"word": "VASO", "hint": "Beber", "category": "Objetos", "difficulty": "easy"},
    {"word": "PLATO", "hint": "Comer", "category": "Objetos", "difficulty": "easy"},
    {"word": "CUCHARA", "hint": "Sopa", "category": "Objetos", "difficulty": "easy"},
    {"word": "TENEDOR", "hint": "Pinchar", "category": "Objetos", "difficulty": "easy"},
    {"word": "CUCHILLO", "hint": "Cortar", "category": "Objetos", "difficulty": "easy"},
    {"word": "SARTÉN", "hint": "Freír", "category": "Objetos", "difficulty": "easy"},
    {"word": "OLLA", "hint": "Cocinar", "category": "Objetos", "difficulty": "easy"},
    {"word": "SILLA", "hint": "Sentar", "category": "Objetos", "difficulty": "easy"},
    {"word": "MESA", "hint": "Mueble", "category": "Objetos", "difficulty": "easy"},
    {"word": "CAMA", "hint": "Dormir", "category": "Objetos", "difficulty": "easy"},
    {"word": "ALMOHADA", "hint": "Suave", "category": "Objetos", "difficulty": "easy"},
    
    # Deportes (20 palabras)
    {"word": "FÚTBOL", "hint": "Balón", "category": "Deportes", "difficulty": "easy"},
    {"word": "BÁSQUETBOL", "hint": "Aro", "category": "Deportes", "difficulty": "easy"},
    {"word": "NATACIÓN", "hint": "Agua", "category": "Deportes", "difficulty": "easy"},
    {"word": "TENIS", "hint": "Raqueta", "category": "Deportes", "difficulty": "easy"},
    {"word": "CICLISMO", "hint": "Bicicleta", "category": "Deportes", "difficulty": "easy"},
    {"word": "BOXEO", "hint": "Guantes", "category": "Deportes", "difficulty": "medium"},
    {"word": "ATLETISMO", "hint": "Carrera", "category": "Deportes", "difficulty": "medium"},
    {"word": "GIMNASIA", "hint": "Flexibilidad", "category": "Deportes", "difficulty": "medium"},
    {"word": "VOLEIBOL", "hint": "Red", "category": "Deportes", "difficulty": "easy"},
    {"word": "BÉISBOL", "hint": "Bat", "category": "Deportes", "difficulty": "easy"},
    {"word": "GOLF", "hint": "Hoyo", "category": "Deportes", "difficulty": "medium"},
    {"word": "HOCKEY", "hint": "Palo", "category": "Deportes", "difficulty": "medium"},
    {"word": "RUGBY", "hint": "Ovalado", "category": "Deportes", "difficulty": "medium"},
    {"word": "KARATE", "hint": "Artes", "category": "Deportes", "difficulty": "medium"},
    {"word": "JUDO", "hint": "Cinturón", "category": "Deportes", "difficulty": "medium"},
    {"word": "ESQUÍ", "hint": "Nieve", "category": "Deportes", "difficulty": "medium"},
    {"word": "SURF", "hint": "Olas", "category": "Deportes", "difficulty": "medium"},
    {"word": "PATINAJE", "hint": "Ruedas", "category": "Deportes", "difficulty": "easy"},
    {"word": "ESCALADA", "hint": "Montaña", "category": "Deportes", "difficulty": "medium"},
    {"word": "YOGA", "hint": "Meditación", "category": "Deportes", "difficulty": "easy"},
    
    # Profesiones (25 palabras)
    {"word": "DOCTOR", "hint": "Medicina", "category": "Profesiones", "difficulty": "easy"},
    {"word": "PROFESOR", "hint": "Enseñanza", "category": "Profesiones", "difficulty": "easy"},
    {"word": "BOMBERO", "hint": "Fuego", "category": "Profesiones", "difficulty": "easy"},
    {"word": "CHEF", "hint": "Cocina", "category": "Profesiones", "difficulty": "easy"},
    {"word": "PILOTO", "hint": "Avión", "category": "Profesiones", "difficulty": "easy"},
    {"word": "ASTRONAUTA", "hint": "Espacio", "category": "Profesiones", "difficulty": "medium"},
    {"word": "POLICÍA", "hint": "Seguridad", "category": "Profesiones", "difficulty": "easy"},
    {"word": "ENFERMERO", "hint": "Hospital", "category": "Profesiones", "difficulty": "easy"},
    {"word": "INGENIERO", "hint": "Construcción", "category": "Profesiones", "difficulty": "medium"},
    {"word": "ARQUITECTO", "hint": "Edificios", "category": "Profesiones", "difficulty": "medium"},
    {"word": "ABOGADO", "hint": "Leyes", "category": "Profesiones", "difficulty": "medium"},
    {"word": "DENTISTA", "hint": "Dientes", "category": "Profesiones", "difficulty": "easy"},
    {"word": "VETERINARIO", "hint": "Animales", "category": "Profesiones", "difficulty": "medium"},
    {"word": "CARPINTERO", "hint": "Madera", "category": "Profesiones", "difficulty": "easy"},
    {"word": "ELECTRICISTA", "hint": "Cables", "category": "Profesiones", "difficulty": "medium"},
    {"word": "PLOMERO", "hint": "Tuberías", "category": "Profesiones", "difficulty": "easy"},
    {"word": "MECÁNICO", "hint": "Autos", "category": "Profesiones", "difficulty": "easy"},
    {"word": "PINTOR", "hint": "Arte", "category": "Profesiones", "difficulty": "easy"},
    {"word": "MÚSICO", "hint": "Instrumentos", "category": "Profesiones", "difficulty": "easy"},
    {"word": "CANTANTE", "hint": "Voz", "category": "Profesiones", "difficulty": "easy"},
    {"word": "ACTOR", "hint": "Cine", "category": "Profesiones", "difficulty": "easy"},
    {"word": "FOTÓGRAFO", "hint": "Imágenes", "category": "Profesiones", "difficulty": "easy"},
    {"word": "PERIODISTA", "hint": "Noticias", "category": "Profesiones", "difficulty": "medium"},
    {"word": "ESCRITOR", "hint": "Libros", "category": "Profesiones", "difficulty": "easy"},
    {"word": "CIENTÍFICO", "hint": "Laboratorio", "category": "Profesiones", "difficulty": "medium"},
    
    # Naturaleza (25 palabras)
    {"word": "ÁRBOL", "hint": "Tronco", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "FLOR", "hint": "Pétalos", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "RÍO", "hint": "Corriente", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "SOL", "hint": "Estrella", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "LUNA", "hint": "Noche", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "VOLCÁN", "hint": "Lava", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "MAR", "hint": "Salado", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "LAGO", "hint": "Dulce", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "CASCADA", "hint": "Caída", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "BOSQUE", "hint": "Árboles", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "SELVA", "hint": "Tropical", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "DESIERTO", "hint": "Arena", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "NUBE", "hint": "Cielo", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "LLUVIA", "hint": "Agua", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "NIEVE", "hint": "Blanca", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "RAYO", "hint": "Tormenta", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "TRUENO", "hint": "Sonido", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "VIENTO", "hint": "Aire", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "ESTRELLA", "hint": "Brilla", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "PLANETA", "hint": "Órbita", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "TIERRA", "hint": "Planeta", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "HOJA", "hint": "Verde", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "RAÍZ", "hint": "Subterránea", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "SEMILLA", "hint": "Planta", "category": "Naturaleza", "difficulty": "easy"},
    {"word": "ROCA", "hint": "Dura", "category": "Naturaleza", "difficulty": "easy"},
    
    # ========== DIFICULTAD MEDIUM (200 palabras) ==========
    
    # Comida Medium (30)
    {"word": "FONDUE", "hint": "Suiza", "category": "Comida", "difficulty": "medium"},
    {"word": "CAVIAR", "hint": "Lujo", "category": "Comida", "difficulty": "medium"},
    {"word": "GAZPACHO", "hint": "Andaluz", "category": "Comida", "difficulty": "medium"},
    {"word": "RISOTTO", "hint": "Arroz", "category": "Comida", "difficulty": "medium"},
    {"word": "RAMEN", "hint": "Fideos", "category": "Comida", "difficulty": "medium"},
    {"word": "TAMAL", "hint": "Maíz", "category": "Comida", "difficulty": "medium"},
    {"word": "FALAFEL", "hint": "Garbanzo", "category": "Comida", "difficulty": "medium"},
    {"word": "CREPE", "hint": "Delgada", "category": "Comida", "difficulty": "medium"},
    {"word": "SOUFFLÉ", "hint": "Esponjoso", "category": "Comida", "difficulty": "medium"},
    {"word": "HUMMUS", "hint": "Árabe", "category": "Comida", "difficulty": "medium"},
    {"word": "GUACAMOLE", "hint": "Aguacate", "category": "Comida", "difficulty": "medium"},
    {"word": "TIRAMISU", "hint": "Mascarpone", "category": "Comida", "difficulty": "medium"},
    {"word": "BAKLAVA", "hint": "Turca", "category": "Comida", "difficulty": "medium"},
    {"word": "PAD THAI", "hint": "Tailandés", "category": "Comida", "difficulty": "medium"},
    {"word": "GOULASH", "hint": "Húngaro", "category": "Comida", "difficulty": "medium"},
    {"word": "SAMOSA", "hint": "India", "category": "Comida", "difficulty": "medium"},
    {"word": "TEMPURA", "hint": "Frita", "category": "Comida", "difficulty": "medium"},
    {"word": "CHURROS", "hint": "Frito", "category": "Comida", "difficulty": "medium"},
    {"word": "QUESADILLA", "hint": "Tortilla", "category": "Comida", "difficulty": "medium"},
    {"word": "ENCHILADA", "hint": "Mexicana", "category": "Comida", "difficulty": "medium"},
    {"word": "CARPACCIO", "hint": "Crudo", "category": "Comida", "difficulty": "medium"},
    {"word": "BRUSCHETTA", "hint": "Tostada", "category": "Comida", "difficulty": "medium"},
    {"word": "MOUSSE", "hint": "Espumoso", "category": "Comida", "difficulty": "medium"},
    {"word": "BAGUETTE", "hint": "Francesa", "category": "Comida", "difficulty": "medium"},
    {"word": "PRETZEL", "hint": "Alemán", "category": "Comida", "difficulty": "medium"},
    {"word": "STRUDEL", "hint": "Austriaco", "category": "Comida", "difficulty": "medium"},
    {"word": "PIEROGI", "hint": "Polaco", "category": "Comida", "difficulty": "medium"},
    {"word": "KEBAB", "hint": "Pincho", "category": "Comida", "difficulty": "medium"},
    {"word": "PASTRAMI", "hint": "Ahumado", "category": "Comida", "difficulty": "medium"},
    {"word": "SASHIMI", "hint": "Pescado", "category": "Comida", "difficulty": "medium"},
    
    # Animales Medium (35)
    {"word": "CAMALEÓN", "hint": "Colores", "category": "Animales", "difficulty": "medium"},
    {"word": "KOALA", "hint": "Eucalipto", "category": "Animales", "difficulty": "medium"},
    {"word": "CANGURO", "hint": "Saltos", "category": "Animales", "difficulty": "medium"},
    {"word": "RINOCERONTE", "hint": "Cuerno", "category": "Animales", "difficulty": "medium"},
    {"word": "HIPOPÓTAMO", "hint": "Grande", "category": "Animales", "difficulty": "medium"},
    {"word": "PANDA", "hint": "Bambú", "category": "Animales", "difficulty": "medium"},
    {"word": "GORILA", "hint": "Primate", "category": "Animales", "difficulty": "medium"},
    {"word": "LEOPARDO", "hint": "Manchas", "category": "Animales", "difficulty": "medium"},
    {"word": "GUEPARDO", "hint": "Veloz", "category": "Animales", "difficulty": "medium"},
    {"word": "PANTERA", "hint": "Negra", "category": "Animales", "difficulty": "medium"},
    {"word": "LOBO", "hint": "Aullido", "category": "Animales", "difficulty": "medium"},
    {"word": "ZORRO", "hint": "Astuto", "category": "Animales", "difficulty": "medium"},
    {"word": "MURCIÉLAGO", "hint": "Nocturno", "category": "Animales", "difficulty": "medium"},
    {"word": "CASTOR", "hint": "Dique", "category": "Animales", "difficulty": "medium"},
    {"word": "NUTRIA", "hint": "Acuática", "category": "Animales", "difficulty": "medium"},
    {"word": "FOCA", "hint": "Ártico", "category": "Animales", "difficulty": "medium"},
    {"word": "MORSA", "hint": "Colmillos", "category": "Animales", "difficulty": "medium"},
    {"word": "ORCA", "hint": "Asesina", "category": "Animales", "difficulty": "medium"},
    {"word": "MEDUSA", "hint": "Tentáculos", "category": "Animales", "difficulty": "medium"},
    {"word": "CALAMAR", "hint": "Tinta", "category": "Animales", "difficulty": "medium"},
    {"word": "ESTRELLA DE MAR", "hint": "Marina", "category": "Animales", "difficulty": "medium"},
    {"word": "ERIZO", "hint": "Púas", "category": "Animales", "difficulty": "medium"},
    {"word": "PAVO REAL", "hint": "Plumas", "category": "Animales", "difficulty": "medium"},
    {"word": "FLAMENCO", "hint": "Rosado", "category": "Animales", "difficulty": "medium"},
    {"word": "PELÍCANO", "hint": "Pico", "category": "Animales", "difficulty": "medium"},
    {"word": "CIGÜEÑA", "hint": "Bebés", "category": "Animales", "difficulty": "medium"},
    {"word": "GRULLA", "hint": "Elegante", "category": "Animales", "difficulty": "medium"},
    {"word": "HALCÓN", "hint": "Caza", "category": "Animales", "difficulty": "medium"},
    {"word": "BUITRE", "hint": "Carroña", "category": "Animales", "difficulty": "medium"},
    {"word": "CUERVO", "hint": "Negro", "category": "Animales", "difficulty": "medium"},
    {"word": "LORO", "hint": "Habla", "category": "Animales", "difficulty": "medium"},
    {"word": "TUCÁN", "hint": "Pico", "category": "Animales", "difficulty": "medium"},
    {"word": "COLIBRÍ", "hint": "Pequeño", "category": "Animales", "difficulty": "medium"},
    {"word": "AVESTRUZ", "hint": "Grande", "category": "Animales", "difficulty": "medium"},
    {"word": "EMÚ", "hint": "Australiano", "category": "Animales", "difficulty": "medium"},
    
    # Lugares Medium (30)
    {"word": "OBSERVATORIO", "hint": "Telescopio", "category": "Lugares", "difficulty": "medium"},
    {"word": "PLANETARIO", "hint": "Estrellas", "category": "Lugares", "difficulty": "medium"},
    {"word": "CATEDRAL", "hint": "Gótica", "category": "Lugares", "difficulty": "medium"},
    {"word": "MEZQUITA", "hint": "Islámica", "category": "Lugares", "difficulty": "medium"},
    {"word": "TEMPLO", "hint": "Sagrado", "category": "Lugares", "difficulty": "medium"},
    {"word": "MONASTERIO", "hint": "Monjes", "category": "Lugares", "difficulty": "medium"},
    {"word": "CONVENTO", "hint": "Monjas", "category": "Lugares", "difficulty": "medium"},
    {"word": "EMBAJADA", "hint": "Diplomacia", "category": "Lugares", "difficulty": "medium"},
    {"word": "CONSULADO", "hint": "Visas", "category": "Lugares", "difficulty": "medium"},
    {"word": "TRIBUNAL", "hint": "Justicia", "category": "Lugares", "difficulty": "medium"},
    {"word": "PRISIÓN", "hint": "Cárcel", "category": "Lugares", "difficulty": "medium"},
    {"word": "CUARTEL", "hint": "Militar", "category": "Lugares", "difficulty": "medium"},
    {"word": "FORTALEZA", "hint": "Defensa", "category": "Lugares", "difficulty": "medium"},
    {"word": "ALCÁZAR", "hint": "Árabe", "category": "Lugares", "difficulty": "medium"},
    {"word": "PALACIO", "hint": "Real", "category": "Lugares", "difficulty": "medium"},
    {"word": "MANSIÓN", "hint": "Lujosa", "category": "Lugares", "difficulty": "medium"},
    {"word": "CABAÑA", "hint": "Rústica", "category": "Lugares", "difficulty": "medium"},
    {"word": "CHOZA", "hint": "Primitiva", "category": "Lugares", "difficulty": "medium"},
    {"word": "GRANERO", "hint": "Granos", "category": "Lugares", "difficulty": "medium"},
    {"word": "MOLINO", "hint": "Viento", "category": "Lugares", "difficulty": "medium"},
    {"word": "FÁBRICA", "hint": "Producción", "category": "Lugares", "difficulty": "medium"},
    {"word": "REFINERÍA", "hint": "Petróleo", "category": "Lugares", "difficulty": "medium"},
    {"word": "ASTILLERO", "hint": "Barcos", "category": "Lugares", "difficulty": "medium"},
    {"word": "MUELLE", "hint": "Puerto", "category": "Lugares", "difficulty": "medium"},
    {"word": "DÁRSENA", "hint": "Portuaria", "category": "Lugares", "difficulty": "medium"},
    {"word": "HANGAR", "hint": "Aviones", "category": "Lugares", "difficulty": "medium"},
    {"word": "SILO", "hint": "Almacenamiento", "category": "Lugares", "difficulty": "medium"},
    {"word": "INVERNADERO", "hint": "Plantas", "category": "Lugares", "difficulty": "medium"},
    {"word": "VIVERO", "hint": "Cultivo", "category": "Lugares", "difficulty": "medium"},
    {"word": "CEMENTERIO", "hint": "Tumbas", "category": "Lugares", "difficulty": "medium"},
    
    # Objetos Medium (35)
    {"word": "BRÚJULA", "hint": "Dirección", "category": "Objetos", "difficulty": "medium"},
    {"word": "TELESCOPIO", "hint": "Estrellas", "category": "Objetos", "difficulty": "medium"},
    {"word": "MICROSCOPIO", "hint": "Pequeño", "category": "Objetos", "difficulty": "medium"},
    {"word": "ESTETOSCOPIO", "hint": "Médico", "category": "Objetos", "difficulty": "medium"},
    {"word": "TERMÓMETRO", "hint": "Temperatura", "category": "Objetos", "difficulty": "medium"},
    {"word": "BARÓMETRO", "hint": "Presión", "category": "Objetos", "difficulty": "medium"},
    {"word": "CRONÓMETRO", "hint": "Precisión", "category": "Objetos", "difficulty": "medium"},
    {"word": "METRÓNOMO", "hint": "Ritmo", "category": "Objetos", "difficulty": "medium"},
    {"word": "VIOLÍN", "hint": "Arco", "category": "Objetos", "difficulty": "medium"},
    {"word": "VIOLONCHELO", "hint": "Grande", "category": "Objetos", "difficulty": "medium"},
    {"word": "ACORDEÓN", "hint": "Fuelle", "category": "Objetos", "difficulty": "medium"},
    {"word": "ARMÓNICA", "hint": "Boca", "category": "Objetos", "difficulty": "medium"},
    {"word": "TROMPETA", "hint": "Viento", "category": "Objetos", "difficulty": "medium"},
    {"word": "SAXOFÓN", "hint": "Jazz", "category": "Objetos", "difficulty": "medium"},
    {"word": "FLAUTA", "hint": "Soplo", "category": "Objetos", "difficulty": "medium"},
    {"word": "BATERÍA", "hint": "Percusión", "category": "Objetos", "difficulty": "medium"},
    {"word": "PIANO", "hint": "Teclas", "category": "Objetos", "difficulty": "medium"},
    {"word": "ARPA", "hint": "Cuerdas", "category": "Objetos", "difficulty": "medium"},
    {"word": "TAMBOR", "hint": "Golpear", "category": "Objetos", "difficulty": "medium"},
    {"word": "MARACAS", "hint": "Sacudir", "category": "Objetos", "difficulty": "medium"},
    {"word": "YUNQUE", "hint": "Herrero", "category": "Objetos", "difficulty": "medium"},
    {"word": "CINCEL", "hint": "Esculpir", "category": "Objetos", "difficulty": "medium"},
    {"word": "TALADRO", "hint": "Perforar", "category": "Objetos", "difficulty": "medium"},
    {"word": "SERRUCHO", "hint": "Cortar", "category": "Objetos", "difficulty": "medium"},
    {"word": "ALICATES", "hint": "Agarrar", "category": "Objetos", "difficulty": "medium"},
    {"word": "PRISMÁTICOS", "hint": "Binoculares", "category": "Objetos", "difficulty": "medium"},
    {"word": "CATALEJO", "hint": "Pirata", "category": "Objetos", "difficulty": "medium"},
    {"word": "SEXTANTE", "hint": "Navegación", "category": "Objetos", "difficulty": "medium"},
    {"word": "ANCLA", "hint": "Barco", "category": "Objetos", "difficulty": "medium"},
    {"word": "TIMÓN", "hint": "Dirección", "category": "Objetos", "difficulty": "medium"},
    {"word": "BRIDA", "hint": "Caballo", "category": "Objetos", "difficulty": "medium"},
    {"word": "HERRADURA", "hint": "Suerte", "category": "Objetos", "difficulty": "medium"},
    {"word": "LÁTIGO", "hint": "Cuero", "category": "Objetos", "difficulty": "medium"},
    {"word": "MACHETE", "hint": "Selva", "category": "Objetos", "difficulty": "medium"},
    {"word": "ANTORCHA", "hint": "Fuego", "category": "Objetos", "difficulty": "medium"},
    
    # Deportes Medium (20)
    {"word": "ESGRIMA", "hint": "Espada", "category": "Deportes", "difficulty": "medium"},
    {"word": "TIRO CON ARCO", "hint": "Diana", "category": "Deportes", "difficulty": "medium"},
    {"word": "HALTEROFILIA", "hint": "Pesas", "category": "Deportes", "difficulty": "medium"},
    {"word": "PENTATLÓN", "hint": "Cinco", "category": "Deportes", "difficulty": "medium"},
    {"word": "TRIATLÓN", "hint": "Tres", "category": "Deportes", "difficulty": "medium"},
    {"word": "MARATÓN", "hint": "Carrera", "category": "Deportes", "difficulty": "medium"},
    {"word": "POLO", "hint": "Caballo", "category": "Deportes", "difficulty": "medium"},
    {"word": "CRÍQUET", "hint": "Inglés", "category": "Deportes", "difficulty": "medium"},
    {"word": "CURLING", "hint": "Hielo", "category": "Deportes", "difficulty": "medium"},
    {"word": "BOBSLED", "hint": "Trineo", "category": "Deportes", "difficulty": "medium"},
    {"word": "SKELETON", "hint": "Descenso", "category": "Deportes", "difficulty": "medium"},
    {"word": "LUGE", "hint": "Pista", "category": "Deportes", "difficulty": "medium"},
    {"word": "BÁDMINTON", "hint": "Pluma", "category": "Deportes", "difficulty": "medium"},
    {"word": "SQUASH", "hint": "Pared", "category": "Deportes", "difficulty": "medium"},
    {"word": "RACQUETBALL", "hint": "Raqueta", "category": "Deportes", "difficulty": "medium"},
    {"word": "BALONMANO", "hint": "Manos", "category": "Deportes", "difficulty": "medium"},
    {"word": "WATERPOLO", "hint": "Acuático", "category": "Deportes", "difficulty": "medium"},
    {"word": "REMO", "hint": "Bote", "category": "Deportes", "difficulty": "medium"},
    {"word": "KAYAK", "hint": "Pala", "category": "Deportes", "difficulty": "medium"},
    {"word": "VELA", "hint": "Náutico", "category": "Deportes", "difficulty": "medium"},
    
    # Profesiones Medium (25)
    {"word": "METEORÓLOGO", "hint": "Clima", "category": "Profesiones", "difficulty": "medium"},
    {"word": "GEÓLOGO", "hint": "Rocas", "category": "Profesiones", "difficulty": "medium"},
    {"word": "ARQUEÓLOGO", "hint": "Excavación", "category": "Profesiones", "difficulty": "medium"},
    {"word": "PALEONTÓLOGO", "hint": "Fósiles", "category": "Profesiones", "difficulty": "medium"},
    {"word": "BIÓLOGO", "hint": "Vida", "category": "Profesiones", "difficulty": "medium"},
    {"word": "QUÍMICO", "hint": "Sustancias", "category": "Profesiones", "difficulty": "medium"},
    {"word": "FÍSICO", "hint": "Materia", "category": "Profesiones", "difficulty": "medium"},
    {"word": "ASTRÓNOMO", "hint": "Cosmos", "category": "Profesiones", "difficulty": "medium"},
    {"word": "MATEMÁTICO", "hint": "Números", "category": "Profesiones", "difficulty": "medium"},
    {"word": "ESTADÍSTICO", "hint": "Datos", "category": "Profesiones", "difficulty": "medium"},
    {"word": "ECONOMISTA", "hint": "Finanzas", "category": "Profesiones", "difficulty": "medium"},
    {"word": "CONTADOR", "hint": "Impuestos", "category": "Profesiones", "difficulty": "medium"},
    {"word": "AUDITOR", "hint": "Revisión", "category": "Profesiones", "difficulty": "medium"},
    {"word": "NOTARIO", "hint": "Documentos", "category": "Profesiones", "difficulty": "medium"},
    {"word": "DIPLOMÁTICO", "hint": "Relaciones", "category": "Profesiones", "difficulty": "medium"},
    {"word": "SOCIÓLOGO", "hint": "Sociedad", "category": "Profesiones", "difficulty": "medium"},
    {"word": "PSICÓLOGO", "hint": "Mente", "category": "Profesiones", "difficulty": "medium"},
    {"word": "PSIQUIATRA", "hint": "Mental", "category": "Profesiones", "difficulty": "medium"},
    {"word": "FARMACÉUTICO", "hint": "Medicamentos", "category": "Profesiones", "difficulty": "medium"},
    {"word": "RADIÓLOGO", "hint": "Rayos", "category": "Profesiones", "difficulty": "medium"},
    {"word": "ANESTESIÓLOGO", "hint": "Anestesia", "category": "Profesiones", "difficulty": "medium"},
    {"word": "CIRUJANO", "hint": "Operación", "category": "Profesiones", "difficulty": "medium"},
    {"word": "CARDIÓLOGO", "hint": "Corazón", "category": "Profesiones", "difficulty": "medium"},
    {"word": "NEURÓLOGO", "hint": "Nervios", "category": "Profesiones", "difficulty": "medium"},
    {"word": "OFTALMÓLOGO", "hint": "Ojos", "category": "Profesiones", "difficulty": "medium"},
    
    # Naturaleza Medium (25)
    {"word": "GLACIAR", "hint": "Hielo", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "ICEBERG", "hint": "Flotante", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "AVALANCHA", "hint": "Nieve", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "TERREMOTO", "hint": "Sismo", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "TSUNAMI", "hint": "Ola", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "HURACÁN", "hint": "Ciclón", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "TORNADO", "hint": "Embudo", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "TIFÓN", "hint": "Asiático", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "MAREMOTO", "hint": "Marino", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "ECLIPSE", "hint": "Sombra", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "ARCOÍRIS", "hint": "Colores", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "AURORA BOREAL", "hint": "Polar", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "COMETA", "hint": "Cola", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "ASTEROIDE", "hint": "Espacio", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "METEORITO", "hint": "Caída", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "NEBULOSA", "hint": "Gas", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "GALAXIA", "hint": "Estrellas", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "AGUJERO NEGRO", "hint": "Gravedad", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "CONSTELACIÓN", "hint": "Patrón", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "EQUINOCCIO", "hint": "Igual", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "SOLSTICIO", "hint": "Extremo", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "FÓSIL", "hint": "Antiguo", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "MINERAL", "hint": "Cristal", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "CUARZO", "hint": "Piedra", "category": "Naturaleza", "difficulty": "medium"},
    {"word": "GEISER", "hint": "Vapor", "category": "Naturaleza", "difficulty": "medium"},
    
    # ========== DIFICULTAD HARD (200 palabras) ==========
    
    # Comida Hard (30)
    {"word": "BOUILLABAISSE", "hint": "Marsella", "category": "Comida", "difficulty": "hard"},
    {"word": "COUSCOUS", "hint": "Magrebí", "category": "Comida", "difficulty": "hard"},
    {"word": "GNOCCHI", "hint": "Papa", "category": "Comida", "difficulty": "hard"},
    {"word": "MOCHI", "hint": "Japonés", "category": "Comida", "difficulty": "hard"},
    {"word": "EDAMAME", "hint": "Soja", "category": "Comida", "difficulty": "hard"},
    {"word": "KIMCHI", "hint": "Coreano", "category": "Comida", "difficulty": "hard"},
    {"word": "BORSCHT", "hint": "Ruso", "category": "Comida", "difficulty": "hard"},
    {"word": "HAGGIS", "hint": "Escocés", "category": "Comida", "difficulty": "hard"},
    {"word": "SCHNITZEL", "hint": "Viena", "category": "Comida", "difficulty": "hard"},
    {"word": "STROGANOFF", "hint": "Cremoso", "category": "Comida", "difficulty": "hard"},
    {"word": "POUTINE", "hint": "Canadiense", "category": "Comida", "difficulty": "hard"},
    {"word": "RATATOUILLE", "hint": "Provenzal", "category": "Comida", "difficulty": "hard"},
    {"word": "CASSOULET", "hint": "Legumbres", "category": "Comida", "difficulty": "hard"},
    {"word": "TAGINE", "hint": "Marroquí", "category": "Comida", "difficulty": "hard"},
    {"word": "BIBIMBAP", "hint": "Cuenco", "category": "Comida", "difficulty": "hard"},
    {"word": "PHO", "hint": "Vietnamita", "category": "Comida", "difficulty": "hard"},
    {"word": "BIRYANI", "hint": "Indio", "category": "Comida", "difficulty": "hard"},
    {"word": "MOUSSAKA", "hint": "Griego", "category": "Comida", "difficulty": "hard"},
    {"word": "TZATZIKI", "hint": "Yogur", "category": "Comida", "difficulty": "hard"},
    {"word": "WASABI", "hint": "Picante", "category": "Comida", "difficulty": "hard"},
    {"word": "ESCARGOT", "hint": "Caracol", "category": "Comida", "difficulty": "hard"},
    {"word": "FOIE GRAS", "hint": "Hígado", "category": "Comida", "difficulty": "hard"},
    {"word": "PROSCIUTTO", "hint": "Italiano", "category": "Comida", "difficulty": "hard"},
    {"word": "PANCETTA", "hint": "Tocino", "category": "Comida", "difficulty": "hard"},
    {"word": "MORTADELA", "hint": "Boloña", "category": "Comida", "difficulty": "hard"},
    {"word": "CHORIZO", "hint": "Ibérico", "category": "Comida", "difficulty": "hard"},
    {"word": "SALAMI", "hint": "Curado", "category": "Comida", "difficulty": "hard"},
    {"word": "PATÉ", "hint": "Pasta", "category": "Comida", "difficulty": "hard"},
    {"word": "TERRINA", "hint": "Molde", "category": "Comida", "difficulty": "hard"},
    {"word": "CHARCUTERÍA", "hint": "Embutidos", "category": "Comida", "difficulty": "hard"},
    
    # Animales Hard (35)
    {"word": "ORNITORRINCO", "hint": "Mamífero", "category": "Animales", "difficulty": "hard"},
    {"word": "EQUIDNA", "hint": "Púas", "category": "Animales", "difficulty": "hard"},
    {"word": "TAPIR", "hint": "Probóscide", "category": "Animales", "difficulty": "hard"},
    {"word": "OKAPI", "hint": "Jirafa", "category": "Animales", "difficulty": "hard"},
    {"word": "LÉMUR", "hint": "Madagascar", "category": "Animales", "difficulty": "hard"},
    {"word": "TARSERO", "hint": "Ojos", "category": "Animales", "difficulty": "hard"},
    {"word": "AYE-AYE", "hint": "Nocturno", "category": "Animales", "difficulty": "hard"},
    {"word": "SURICATA", "hint": "Vigilante", "category": "Animales", "difficulty": "hard"},
    {"word": "ARMADILLO", "hint": "Armadura", "category": "Animales", "difficulty": "hard"},
    {"word": "OSO HORMIGUERO", "hint": "Lengua", "category": "Animales", "difficulty": "hard"},
    {"word": "PEREZOSO", "hint": "Lento", "category": "Animales", "difficulty": "hard"},
    {"word": "CAPIBARA", "hint": "Roedor", "category": "Animales", "difficulty": "hard"},
    {"word": "WOMBAT", "hint": "Australiano", "category": "Animales", "difficulty": "hard"},
    {"word": "DEMONIO DE TASMANIA", "hint": "Marsupial", "category": "Animales", "difficulty": "hard"},
    {"word": "NUMBAT", "hint": "Termitas", "category": "Animales", "difficulty": "hard"},
    {"word": "QUOKKA", "hint": "Sonrisa", "category": "Animales", "difficulty": "hard"},
    {"word": "DINGO", "hint": "Salvaje", "category": "Animales", "difficulty": "hard"},
    {"word": "NARVAL", "hint": "Unicornio", "category": "Animales", "difficulty": "hard"},
    {"word": "BELUGA", "hint": "Blanca", "category": "Animales", "difficulty": "hard"},
    {"word": "DUGONGO", "hint": "Sirénido", "category": "Animales", "difficulty": "hard"},
    {"word": "MANATÍ", "hint": "Herbívoro", "category": "Animales", "difficulty": "hard"},
    {"word": "MANTARRAYA", "hint": "Aletas", "category": "Animales", "difficulty": "hard"},
    {"word": "RÉMORA", "hint": "Adherida", "category": "Animales", "difficulty": "hard"},
    {"word": "PEZ GLOBO", "hint": "Infla", "category": "Animales", "difficulty": "hard"},
    {"word": "AXOLOTE", "hint": "Regeneración", "category": "Animales", "difficulty": "hard"},
    {"word": "SALAMANDRA", "hint": "Anfibio", "category": "Animales", "difficulty": "hard"},
    {"word": "TRITÓN", "hint": "Acuático", "category": "Animales", "difficulty": "hard"},
    {"word": "GECKO", "hint": "Adhesivo", "category": "Animales", "difficulty": "hard"},
    {"word": "IGUANA", "hint": "Cresta", "category": "Animales", "difficulty": "hard"},
    {"word": "DRAGÓN DE KOMODO", "hint": "Gigante", "category": "Animales", "difficulty": "hard"},
    {"word": "ANACONDA", "hint": "Constrictora", "category": "Animales", "difficulty": "hard"},
    {"word": "BOA", "hint": "Tropical", "category": "Animales", "difficulty": "hard"},
    {"word": "PITÓN", "hint": "Asiática", "category": "Animales", "difficulty": "hard"},
    {"word": "COBRA", "hint": "Capucha", "category": "Animales", "difficulty": "hard"},
    {"word": "MAMBA", "hint": "Africana", "category": "Animales", "difficulty": "hard"},
    
    # Lugares Hard (30)
    {"word": "MAUSOLEO", "hint": "Sepulcro", "category": "Lugares", "difficulty": "hard"},
    {"word": "NECRÓPOLIS", "hint": "Cementerio", "category": "Lugares", "difficulty": "hard"},
    {"word": "CRIPTA", "hint": "Subterránea", "category": "Lugares", "difficulty": "hard"},
    {"word": "CATACUMBA", "hint": "Túneles", "category": "Lugares", "difficulty": "hard"},
    {"word": "OBELISCO", "hint": "Monumento", "category": "Lugares", "difficulty": "hard"},
    {"word": "ZIGURAT", "hint": "Mesopotamia", "category": "Lugares", "difficulty": "hard"},
    {"word": "PAGODA", "hint": "Oriental", "category": "Lugares", "difficulty": "hard"},
    {"word": "SINAGOGA", "hint": "Judía", "category": "Lugares", "difficulty": "hard"},
    {"word": "BASÍLICA", "hint": "Romana", "category": "Lugares", "difficulty": "hard"},
    {"word": "ABADÍA", "hint": "Monástica", "category": "Lugares", "difficulty": "hard"},
    {"word": "SANTUARIO", "hint": "Sagrado", "category": "Lugares", "difficulty": "hard"},
    {"word": "ERMITA", "hint": "Solitaria", "category": "Lugares", "difficulty": "hard"},
    {"word": "CLAUSTRO", "hint": "Patio", "category": "Lugares", "difficulty": "hard"},
    {"word": "REFECTORIO", "hint": "Comedor", "category": "Lugares", "difficulty": "hard"},
    {"word": "SCRIPTORIUM", "hint": "Manuscritos", "category": "Lugares", "difficulty": "hard"},
    {"word": "ÁGORA", "hint": "Griega", "category": "Lugares", "difficulty": "hard"},
    {"word": "FORO", "hint": "Romano", "category": "Lugares", "difficulty": "hard"},
    {"word": "ACRÓPOLIS", "hint": "Elevada", "category": "Lugares", "difficulty": "hard"},
    {"word": "COLISEO", "hint": "Anfiteatro", "category": "Lugares", "difficulty": "hard"},
    {"word": "HIPÓDROMO", "hint": "Carreras", "category": "Lugares", "difficulty": "hard"},
    {"word": "ACUEDUCTO", "hint": "Agua", "category": "Lugares", "difficulty": "hard"},
    {"word": "VIADUCTO", "hint": "Valle", "category": "Lugares", "difficulty": "hard"},
    {"word": "CAMPANARIO", "hint": "Campanas", "category": "Lugares", "difficulty": "hard"},
    {"word": "ALMINAR", "hint": "Minarete", "category": "Lugares", "difficulty": "hard"},
    {"word": "MINARETE", "hint": "Torre", "category": "Lugares", "difficulty": "hard"},
    {"word": "ATALAYA", "hint": "Vigilancia", "category": "Lugares", "difficulty": "hard"},
    {"word": "BARBACANA", "hint": "Defensiva", "category": "Lugares", "difficulty": "hard"},
    {"word": "ALMENA", "hint": "Muralla", "category": "Lugares", "difficulty": "hard"},
    {"word": "BASTIÓN", "hint": "Fortificación", "category": "Lugares", "difficulty": "hard"},
    {"word": "CIUDADELA", "hint": "Fortaleza", "category": "Lugares", "difficulty": "hard"},
    
    # Objetos Hard (35)
    {"word": "ASTROLABIO", "hint": "Navegación", "category": "Objetos", "difficulty": "hard"},
    {"word": "CUADRANTE", "hint": "Medición", "category": "Objetos", "difficulty": "hard"},
    {"word": "OCTANTE", "hint": "Ángulos", "category": "Objetos", "difficulty": "hard"},
    {"word": "GONIÓMETRO", "hint": "Geometría", "category": "Objetos", "difficulty": "hard"},
    {"word": "TEODOLITO", "hint": "Topografía", "category": "Objetos", "difficulty": "hard"},
    {"word": "PLOMADA", "hint": "Vertical", "category": "Objetos", "difficulty": "hard"},
    {"word": "ESCUADRA", "hint": "Ángulo", "category": "Objetos", "difficulty": "hard"},
    {"word": "COMPÁS", "hint": "Círculo", "category": "Objetos", "difficulty": "hard"},
    {"word": "TRANSPORTADOR", "hint": "Grados", "category": "Objetos", "difficulty": "hard"},
    {"word": "CALIBRADOR", "hint": "Precisión", "category": "Objetos", "difficulty": "hard"},
    {"word": "MICRÓMETRO", "hint": "Medida", "category": "Objetos", "difficulty": "hard"},
    {"word": "VERNIER", "hint": "Escala", "category": "Objetos", "difficulty": "hard"},
    {"word": "NIVEL", "hint": "Horizontal", "category": "Objetos", "difficulty": "hard"},
    {"word": "CLAVECÍN", "hint": "Barroco", "category": "Objetos", "difficulty": "hard"},
    {"word": "CLAVICORDIO", "hint": "Antiguo", "category": "Objetos", "difficulty": "hard"},
    {"word": "ÓRGANO", "hint": "Tubos", "category": "Objetos", "difficulty": "hard"},
    {"word": "GAITA", "hint": "Escocesa", "category": "Objetos", "difficulty": "hard"},
    {"word": "OBOE", "hint": "Lengüeta", "category": "Objetos", "difficulty": "hard"},
    {"word": "FAGOT", "hint": "Grave", "category": "Objetos", "difficulty": "hard"},
    {"word": "CLARINETE", "hint": "Madera", "category": "Objetos", "difficulty": "hard"},
    {"word": "TUBA", "hint": "Grave", "category": "Objetos", "difficulty": "hard"},
    {"word": "TROMBÓN", "hint": "Varas", "category": "Objetos", "difficulty": "hard"},
    {"word": "CORNETA", "hint": "Militar", "category": "Objetos", "difficulty": "hard"},
    {"word": "TÍMPANO", "hint": "Orquesta", "category": "Objetos", "difficulty": "hard"},
    {"word": "XILÓFONO", "hint": "Láminas", "category": "Objetos", "difficulty": "hard"},
    {"word": "GLOCKENSPIEL", "hint": "Campanas", "category": "Objetos", "difficulty": "hard"},
    {"word": "VIBRÁFONO", "hint": "Resonadores", "category": "Objetos", "difficulty": "hard"},
    {"word": "MARIMBA", "hint": "Percusión", "category": "Objetos", "difficulty": "hard"},
    {"word": "LAÚD", "hint": "Medieval", "category": "Objetos", "difficulty": "hard"},
    {"word": "MANDOLINA", "hint": "Cuerdas", "category": "Objetos", "difficulty": "hard"},
    {"word": "BALALAICA", "hint": "Rusa", "category": "Objetos", "difficulty": "hard"},
    {"word": "CÍTARA", "hint": "Antigua", "category": "Objetos", "difficulty": "hard"},
    {"word": "LIRA", "hint": "Griega", "category": "Objetos", "difficulty": "hard"},
    {"word": "SITAR", "hint": "India", "category": "Objetos", "difficulty": "hard"},
    {"word": "SHAMISEN", "hint": "Japonés", "category": "Objetos", "difficulty": "hard"},
    
    # Deportes Hard (20)
    {"word": "BIATLÓN", "hint": "Esquí", "category": "Deportes", "difficulty": "hard"},
    {"word": "HEPTATLÓN", "hint": "Siete", "category": "Deportes", "difficulty": "hard"},
    {"word": "DECATLÓN", "hint": "Diez", "category": "Deportes", "difficulty": "hard"},
    {"word": "STEEPLECHASE", "hint": "Obstáculos", "category": "Deportes", "difficulty": "hard"},
    {"word": "SALTO CON PÉRTIGA", "hint": "Altura", "category": "Deportes", "difficulty": "hard"},
    {"word": "LANZAMIENTO DE JABALINA", "hint": "Lanza", "category": "Deportes", "difficulty": "hard"},
    {"word": "LANZAMIENTO DE MARTILLO", "hint": "Gira", "category": "Deportes", "difficulty": "hard"},
    {"word": "LANZAMIENTO DE DISCO", "hint": "Circular", "category": "Deportes", "difficulty": "hard"},
    {"word": "LANZAMIENTO DE PESO", "hint": "Bola", "category": "Deportes", "difficulty": "hard"},
    {"word": "PARKOUR", "hint": "Urbano", "category": "Deportes", "difficulty": "hard"},
    {"word": "KITESURF", "hint": "Cometa", "category": "Deportes", "difficulty": "hard"},
    {"word": "WINDSURF", "hint": "Vela", "category": "Deportes", "difficulty": "hard"},
    {"word": "WAKEBOARD", "hint": "Lancha", "category": "Deportes", "difficulty": "hard"},
    {"word": "SNOWBOARD", "hint": "Nieve", "category": "Deportes", "difficulty": "hard"},
    {"word": "SKATEBOARD", "hint": "Tabla", "category": "Deportes", "difficulty": "hard"},
    {"word": "LONGBOARD", "hint": "Larga", "category": "Deportes", "difficulty": "hard"},
    {"word": "BMX", "hint": "Acrobacia", "category": "Deportes", "difficulty": "hard"},
    {"word": "MOTOCROSS", "hint": "Tierra", "category": "Deportes", "difficulty": "hard"},
    {"word": "RALLYCROSS", "hint": "Mixto", "category": "Deportes", "difficulty": "hard"},
    {"word": "SLALOM", "hint": "Zigzag", "category": "Deportes", "difficulty": "hard"},
    
    # Profesiones Hard (25)
    {"word": "EPIDEMIÓLOGO", "hint": "Enfermedades", "category": "Profesiones", "difficulty": "hard"},
    {"word": "ENDOCRINÓLOGO", "hint": "Hormonas", "category": "Profesiones", "difficulty": "hard"},
    {"word": "GASTROENTERÓLOGO", "hint": "Digestivo", "category": "Profesiones", "difficulty": "hard"},
    {"word": "NEFRÓLOGO", "hint": "Riñones", "category": "Profesiones", "difficulty": "hard"},
    {"word": "NEUMÓLOGO", "hint": "Pulmones", "category": "Profesiones", "difficulty": "hard"},
    {"word": "DERMATÓLOGO", "hint": "Piel", "category": "Profesiones", "difficulty": "hard"},
    {"word": "REUMATÓLOGO", "hint": "Articulaciones", "category": "Profesiones", "difficulty": "hard"},
    {"word": "ONCÓLOGO", "hint": "Cáncer", "category": "Profesiones", "difficulty": "hard"},
    {"word": "HEMATÓLOGO", "hint": "Sangre", "category": "Profesiones", "difficulty": "hard"},
    {"word": "INMUNÓLOGO", "hint": "Defensas", "category": "Profesiones", "difficulty": "hard"},
    {"word": "PATÓLOGO", "hint": "Enfermedades", "category": "Profesiones", "difficulty": "hard"},
    {"word": "TOXICÓLOGO", "hint": "Venenos", "category": "Profesiones", "difficulty": "hard"},
    {"word": "GENETISTA", "hint": "ADN", "category": "Profesiones", "difficulty": "hard"},
    {"word": "BIOQUÍMICO", "hint": "Molecular", "category": "Profesiones", "difficulty": "hard"},
    {"word": "ASTROFÍSICO", "hint": "Universo", "category": "Profesiones", "difficulty": "hard"},
    {"word": "COSMÓLOGO", "hint": "Cosmos", "category": "Profesiones", "difficulty": "hard"},
    {"word": "OCEANÓGRAFO", "hint": "Océanos", "category": "Profesiones", "difficulty": "hard"},
    {"word": "SISMÓLOGO", "hint": "Terremotos", "category": "Profesiones", "difficulty": "hard"},
    {"word": "VULCANÓLOGO", "hint": "Volcanes", "category": "Profesiones", "difficulty": "hard"},
    {"word": "ESPELEÓLOGO", "hint": "Cuevas", "category": "Profesiones", "difficulty": "hard"},
    {"word": "CARTÓGRAFO", "hint": "Mapas", "category": "Profesiones", "difficulty": "hard"},
    {"word": "TOPÓGRAFO", "hint": "Terreno", "category": "Profesiones", "difficulty": "hard"},
    {"word": "AGRIMENSOR", "hint": "Medición", "category": "Profesiones", "difficulty": "hard"},
    {"word": "ORFEBRE", "hint": "Metales", "category": "Profesiones", "difficulty": "hard"},
    {"word": "RELOJERO", "hint": "Mecanismos", "category": "Profesiones", "difficulty": "hard"},
    
    # Naturaleza Hard (25)
    {"word": "ESTALACTITA", "hint": "Cuelga", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "ESTALAGMITA", "hint": "Crece", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "CALDERA", "hint": "Volcánica", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "FUMAROLA", "hint": "Gases", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "GÉISER", "hint": "Erupción", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "DELTA", "hint": "Desembocadura", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "ESTUARIO", "hint": "Río", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "FIORDO", "hint": "Glaciar", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "ARCHIPIÉLAGO", "hint": "Islas", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "ATOLÓN", "hint": "Coral", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "ARRECIFE", "hint": "Coral", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "MANGLAR", "hint": "Raíces", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "TUNDRA", "hint": "Polar", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "TAIGA", "hint": "Boreal", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "SABANA", "hint": "Africana", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "ESTEPA", "hint": "Pradera", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "PAMPA", "hint": "Sudamericana", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "PÁRAMO", "hint": "Andino", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "MESETA", "hint": "Plana", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "ALTIPLANO", "hint": "Elevada", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "CAÑÓN", "hint": "Profundo", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "DESFILADERO", "hint": "Estrecho", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "BARRANCO", "hint": "Precipicio", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "ACANTILADO", "hint": "Costa", "category": "Naturaleza", "difficulty": "hard"},
    {"word": "PENÍNSULA", "hint": "Tierra", "category": "Naturaleza", "difficulty": "hard"},
    
    # ========== INFORMÁTICA MEDIUM (100 palabras) ==========
    
    {"word": "INTERNET", "hint": "Red", "category": "Informática", "difficulty": "medium"},
    {"word": "NAVEGADOR", "hint": "Browser", "category": "Informática", "difficulty": "medium"},
    {"word": "SOFTWARE", "hint": "Programa", "category": "Informática", "difficulty": "medium"},
    {"word": "HARDWARE", "hint": "Físico", "category": "Informática", "difficulty": "medium"},
    {"word": "SERVIDOR", "hint": "Server", "category": "Informática", "difficulty": "medium"},
    {"word": "CLIENTE", "hint": "Usuario", "category": "Informática", "difficulty": "medium"},
    {"word": "ROUTER", "hint": "Enrutador", "category": "Informática", "difficulty": "medium"},
    {"word": "MODEM", "hint": "Modulador", "category": "Informática", "difficulty": "medium"},
    {"word": "FIREWALL", "hint": "Protección", "category": "Informática", "difficulty": "medium"},
    {"word": "ANTIVIRUS", "hint": "Seguridad", "category": "Informática", "difficulty": "medium"},
    {"word": "MALWARE", "hint": "Virus", "category": "Informática", "difficulty": "medium"},
    {"word": "PHISHING", "hint": "Fraude", "category": "Informática", "difficulty": "medium"},
    {"word": "SPAM", "hint": "Basura", "category": "Informática", "difficulty": "medium"},
    {"word": "COOKIE", "hint": "Galleta", "category": "Informática", "difficulty": "medium"},
    {"word": "CACHE", "hint": "Temporal", "category": "Informática", "difficulty": "medium"},
    {"word": "BACKUP", "hint": "Respaldo", "category": "Informática", "difficulty": "medium"},
    {"word": "NUBE", "hint": "Cloud", "category": "Informática", "difficulty": "medium"},
    {"word": "STREAMING", "hint": "Transmisión", "category": "Informática", "difficulty": "medium"},
    {"word": "PIXEL", "hint": "Punto", "category": "Informática", "difficulty": "medium"},
    {"word": "RESOLUCIÓN", "hint": "Calidad", "category": "Informática", "difficulty": "medium"},
    {"word": "MONITOR", "hint": "Pantalla", "category": "Informática", "difficulty": "medium"},
    {"word": "TECLADO", "hint": "Teclas", "category": "Informática", "difficulty": "medium"},
    {"word": "MOUSE", "hint": "Ratón", "category": "Informática", "difficulty": "medium"},
    {"word": "TOUCHPAD", "hint": "Táctil", "category": "Informática", "difficulty": "medium"},
    {"word": "PROCESADOR", "hint": "CPU", "category": "Informática", "difficulty": "medium"},
    {"word": "MEMORIA RAM", "hint": "Temporal", "category": "Informática", "difficulty": "medium"},
    {"word": "DISCO DURO", "hint": "Almacenamiento", "category": "Informática", "difficulty": "medium"},
    {"word": "USB", "hint": "Puerto", "category": "Informática", "difficulty": "medium"},
    {"word": "HDMI", "hint": "Cable", "category": "Informática", "difficulty": "medium"},
    {"word": "BLUETOOTH", "hint": "Inalámbrico", "category": "Informática", "difficulty": "medium"},
    {"word": "WIFI", "hint": "Inalámbrico", "category": "Informática", "difficulty": "medium"},
    {"word": "ETHERNET", "hint": "Cable", "category": "Informática", "difficulty": "medium"},
    {"word": "BANDWIDTH", "hint": "Ancho", "category": "Informática", "difficulty": "medium"},
    {"word": "LATENCIA", "hint": "Retraso", "category": "Informática", "difficulty": "medium"},
    {"word": "PING", "hint": "Tiempo", "category": "Informática", "difficulty": "medium"},
    {"word": "DOWNLOAD", "hint": "Descarga", "category": "Informática", "difficulty": "medium"},
    {"word": "UPLOAD", "hint": "Subida", "category": "Informática", "difficulty": "medium"},
    {"word": "CARPETA", "hint": "Folder", "category": "Informática", "difficulty": "medium"},
    {"word": "ARCHIVO", "hint": "File", "category": "Informática", "difficulty": "medium"},
    {"word": "ZIP", "hint": "Comprimido", "category": "Informática", "difficulty": "medium"},
    {"word": "PDF", "hint": "Documento", "category": "Informática", "difficulty": "medium"},
    {"word": "EXCEL", "hint": "Hojas", "category": "Informática", "difficulty": "medium"},
    {"word": "POWERPOINT", "hint": "Diapositivas", "category": "Informática", "difficulty": "medium"},
    {"word": "WORD", "hint": "Texto", "category": "Informática", "difficulty": "medium"},
    {"word": "GMAIL", "hint": "Correo", "category": "Informática", "difficulty": "medium"},
    {"word": "YOUTUBE", "hint": "Videos", "category": "Informática", "difficulty": "medium"},
    {"word": "FACEBOOK", "hint": "Social", "category": "Informática", "difficulty": "medium"},
    {"word": "INSTAGRAM", "hint": "Fotos", "category": "Informática", "difficulty": "medium"},
    {"word": "TWITTER", "hint": "Tweets", "category": "Informática", "difficulty": "medium"},
    {"word": "WHATSAPP", "hint": "Mensajes", "category": "Informática", "difficulty": "medium"},
    {"word": "ZOOM", "hint": "Videollamada", "category": "Informática", "difficulty": "medium"},
    {"word": "DISCORD", "hint": "Chat", "category": "Informática", "difficulty": "medium"},
    {"word": "GITHUB", "hint": "Repositorio", "category": "Informática", "difficulty": "medium"},
    {"word": "LINKEDIN", "hint": "Profesional", "category": "Informática", "difficulty": "medium"},
    {"word": "NETFLIX", "hint": "Streaming", "category": "Informática", "difficulty": "medium"},
    {"word": "SPOTIFY", "hint": "Música", "category": "Informática", "difficulty": "medium"},
    {"word": "TWITCH", "hint": "Streaming", "category": "Informática", "difficulty": "medium"},
    {"word": "REDDIT", "hint": "Foros", "category": "Informática", "difficulty": "medium"},
    {"word": "WIKIPEDIA", "hint": "Enciclopedia", "category": "Informática", "difficulty": "medium"},
    {"word": "GOOGLE", "hint": "Buscador", "category": "Informática", "difficulty": "medium"},
    {"word": "CHROME", "hint": "Browser", "category": "Informática", "difficulty": "medium"},
    {"word": "FIREFOX", "hint": "Navegador", "category": "Informática", "difficulty": "medium"},
    {"word": "SAFARI", "hint": "Apple", "category": "Informática", "difficulty": "medium"},
    {"word": "WINDOWS", "hint": "Microsoft", "category": "Informática", "difficulty": "medium"},
    {"word": "LINUX", "hint": "Open", "category": "Informática", "difficulty": "medium"},
    {"word": "ANDROID", "hint": "Sistema", "category": "Informática", "difficulty": "medium"},
    {"word": "IOS", "hint": "Apple", "category": "Informática", "difficulty": "medium"},
    {"word": "APP", "hint": "Aplicación", "category": "Informática", "difficulty": "medium"},
    {"word": "EMOJI", "hint": "Emoticón", "category": "Informática", "difficulty": "medium"},
    {"word": "GIF", "hint": "Animado", "category": "Informática", "difficulty": "medium"},
    {"word": "MEME", "hint": "Viral", "category": "Informática", "difficulty": "medium"},
    {"word": "HASHTAG", "hint": "Etiqueta", "category": "Informática", "difficulty": "medium"},
    {"word": "LIKE", "hint": "Gustar", "category": "Informática", "difficulty": "medium"},
    {"word": "SHARE", "hint": "Compartir", "category": "Informática", "difficulty": "medium"},
    {"word": "FOLLOW", "hint": "Seguir", "category": "Informática", "difficulty": "medium"},
    {"word": "SELFIE", "hint": "Autofoto", "category": "Informática", "difficulty": "medium"},
    {"word": "PHOTOSHOP", "hint": "Edición", "category": "Informática", "difficulty": "medium"},
    {"word": "ILLUSTRATOR", "hint": "Vectorial", "category": "Informática", "difficulty": "medium"},
    {"word": "AUTOCAD", "hint": "Diseño", "category": "Informática", "difficulty": "medium"},
    {"word": "MINECRAFT", "hint": "Bloques", "category": "Informática", "difficulty": "medium"},
    {"word": "FORTNITE", "hint": "Battle", "category": "Informática", "difficulty": "medium"},
    {"word": "PLAYSTATION", "hint": "Consola", "category": "Informática", "difficulty": "medium"},
    {"word": "XBOX", "hint": "Microsoft", "category": "Informática", "difficulty": "medium"},
    {"word": "NINTENDO", "hint": "Switch", "category": "Informática", "difficulty": "medium"},
    {"word": "STEAM", "hint": "Juegos", "category": "Informática", "difficulty": "medium"},
    {"word": "WEBCAM", "hint": "Cámara", "category": "Informática", "difficulty": "medium"},
    {"word": "MICRÓFONO", "hint": "Audio", "category": "Informática", "difficulty": "medium"},
    {"word": "AURICULARES", "hint": "Sonido", "category": "Informática", "difficulty": "medium"},
    {"word": "ALTAVOZ", "hint": "Bocina", "category": "Informática", "difficulty": "medium"},
    {"word": "IMPRESORA", "hint": "Papel", "category": "Informática", "difficulty": "medium"},
    {"word": "ESCÁNER", "hint": "Digitalizar", "category": "Informática", "difficulty": "medium"},
    {"word": "PROYECTOR", "hint": "Imagen", "category": "Informática", "difficulty": "medium"},
    {"word": "TABLET", "hint": "Portátil", "category": "Informática", "difficulty": "medium"},
    {"word": "LAPTOP", "hint": "Portátil", "category": "Informática", "difficulty": "medium"},
    {"word": "DESKTOP", "hint": "Escritorio", "category": "Informática", "difficulty": "medium"},
    {"word": "SMARTPHONE", "hint": "Inteligente", "category": "Informática", "difficulty": "medium"},
    {"word": "SMARTWATCH", "hint": "Reloj", "category": "Informática", "difficulty": "medium"},
    
    # ========== INFORMÁTICA HARD (100 palabras) ==========
    
    {"word": "ALGORITMO", "hint": "Lógica", "category": "Informática", "difficulty": "hard"},
    {"word": "BACKEND", "hint": "Servidor", "category": "Informática", "difficulty": "hard"},
    {"word": "FRONTEND", "hint": "Cliente", "category": "Informática", "difficulty": "hard"},
    {"word": "FULLSTACK", "hint": "Completo", "category": "Informática", "difficulty": "hard"},
    {"word": "API", "hint": "Interfaz", "category": "Informática", "difficulty": "hard"},
    {"word": "REST", "hint": "Arquitectura", "category": "Informática", "difficulty": "hard"},
    {"word": "JSON", "hint": "Formato", "category": "Informática", "difficulty": "hard"},
    {"word": "XML", "hint": "Markup", "category": "Informática", "difficulty": "hard"},
    {"word": "HTML", "hint": "Web", "category": "Informática", "difficulty": "hard"},
    {"word": "CSS", "hint": "Estilos", "category": "Informática", "difficulty": "hard"},
    {"word": "JAVASCRIPT", "hint": "Scripting", "category": "Informática", "difficulty": "hard"},
    {"word": "PYTHON", "hint": "Lenguaje", "category": "Informática", "difficulty": "hard"},
    {"word": "JAVA", "hint": "Programación", "category": "Informática", "difficulty": "hard"},
    {"word": "C++", "hint": "Compilado", "category": "Informática", "difficulty": "hard"},
    {"word": "PHP", "hint": "Servidor", "category": "Informática", "difficulty": "hard"},
    {"word": "SQL", "hint": "Consultas", "category": "Informática", "difficulty": "hard"},
    {"word": "DATABASE", "hint": "Datos", "category": "Informática", "difficulty": "hard"},
    {"word": "MYSQL", "hint": "Relacional", "category": "Informática", "difficulty": "hard"},
    {"word": "MONGODB", "hint": "NoSQL", "category": "Informática", "difficulty": "hard"},
    {"word": "POSTGRESQL", "hint": "Relacional", "category": "Informática", "difficulty": "hard"},
    {"word": "REDIS", "hint": "Cache", "category": "Informática", "difficulty": "hard"},
    {"word": "DOCKER", "hint": "Contenedores", "category": "Informática", "difficulty": "hard"},
    {"word": "KUBERNETES", "hint": "Orquestación", "category": "Informática", "difficulty": "hard"},
    {"word": "GIT", "hint": "Versiones", "category": "Informática", "difficulty": "hard"},
    {"word": "GITHUB", "hint": "Repositorio", "category": "Informática", "difficulty": "hard"},
    {"word": "GITLAB", "hint": "DevOps", "category": "Informática", "difficulty": "hard"},
    {"word": "CI/CD", "hint": "Integración", "category": "Informática", "difficulty": "hard"},
    {"word": "DEVOPS", "hint": "Desarrollo", "category": "Informática", "difficulty": "hard"},
    {"word": "AGILE", "hint": "Metodología", "category": "Informática", "difficulty": "hard"},
    {"word": "SCRUM", "hint": "Framework", "category": "Informática", "difficulty": "hard"},
    {"word": "SPRINT", "hint": "Iteración", "category": "Informática", "difficulty": "hard"},
    {"word": "KANBAN", "hint": "Tablero", "category": "Informática", "difficulty": "hard"},
    {"word": "REACT", "hint": "Librería", "category": "Informática", "difficulty": "hard"},
    {"word": "ANGULAR", "hint": "Framework", "category": "Informática", "difficulty": "hard"},
    {"word": "VUE", "hint": "Frontend", "category": "Informática", "difficulty": "hard"},
    {"word": "NODE.JS", "hint": "Runtime", "category": "Informática", "difficulty": "hard"},
    {"word": "EXPRESS", "hint": "Framework", "category": "Informática", "difficulty": "hard"},
    {"word": "DJANGO", "hint": "Python", "category": "Informática", "difficulty": "hard"},
    {"word": "FLASK", "hint": "Microframework", "category": "Informática", "difficulty": "hard"},
    {"word": "SPRING", "hint": "Java", "category": "Informática", "difficulty": "hard"},
    {"word": "LARAVEL", "hint": "PHP", "category": "Informática", "difficulty": "hard"},
    {"word": "RUBY ON RAILS", "hint": "Framework", "category": "Informática", "difficulty": "hard"},
    {"word": "TYPESCRIPT", "hint": "Tipado", "category": "Informática", "difficulty": "hard"},
    {"word": "WEBPACK", "hint": "Bundler", "category": "Informática", "difficulty": "hard"},
    {"word": "BABEL", "hint": "Transpilador", "category": "Informática", "difficulty": "hard"},
    {"word": "NPM", "hint": "Paquetes", "category": "Informática", "difficulty": "hard"},
    {"word": "YARN", "hint": "Gestor", "category": "Informática", "difficulty": "hard"},
    {"word": "REDUX", "hint": "Estado", "category": "Informática", "difficulty": "hard"},
    {"word": "GRAPHQL", "hint": "Query", "category": "Informática", "difficulty": "hard"},
    {"word": "WEBSOCKET", "hint": "Tiempo", "category": "Informática", "difficulty": "hard"},
    {"word": "AJAX", "hint": "Asíncrono", "category": "Informática", "difficulty": "hard"},
    {"word": "JWT", "hint": "Token", "category": "Informática", "difficulty": "hard"},
    {"word": "OAUTH", "hint": "Autenticación", "category": "Informática", "difficulty": "hard"},
    {"word": "SSL", "hint": "Seguridad", "category": "Informática", "difficulty": "hard"},
    {"word": "TLS", "hint": "Encriptación", "category": "Informática", "difficulty": "hard"},
    {"word": "HTTPS", "hint": "Seguro", "category": "Informática", "difficulty": "hard"},
    {"word": "VPN", "hint": "Virtual", "category": "Informática", "difficulty": "hard"},
    {"word": "PROXY", "hint": "Intermediario", "category": "Informática", "difficulty": "hard"},
    {"word": "DNS", "hint": "Nombres", "category": "Informática", "difficulty": "hard"},
    {"word": "IP", "hint": "Dirección", "category": "Informática", "difficulty": "hard"},
    {"word": "TCP", "hint": "Protocolo", "category": "Informática", "difficulty": "hard"},
    {"word": "UDP", "hint": "Paquetes", "category": "Informática", "difficulty": "hard"},
    {"word": "HTTP", "hint": "Protocolo", "category": "Informática", "difficulty": "hard"},
    {"word": "FTP", "hint": "Transferencia", "category": "Informática", "difficulty": "hard"},
    {"word": "SSH", "hint": "Remoto", "category": "Informática", "difficulty": "hard"},
    {"word": "BASH", "hint": "Terminal", "category": "Informática", "difficulty": "hard"},
    {"word": "POWERSHELL", "hint": "Windows", "category": "Informática", "difficulty": "hard"},
    {"word": "TERMINAL", "hint": "Comandos", "category": "Informática", "difficulty": "hard"},
    {"word": "CLI", "hint": "Interfaz", "category": "Informática", "difficulty": "hard"},
    {"word": "GUI", "hint": "Gráfica", "category": "Informática", "difficulty": "hard"},
    {"word": "IDE", "hint": "Desarrollo", "category": "Informática", "difficulty": "hard"},
    {"word": "VSCODE", "hint": "Editor", "category": "Informática", "difficulty": "hard"},
    {"word": "INTELLIJ", "hint": "IDE", "category": "Informática", "difficulty": "hard"},
    {"word": "ECLIPSE", "hint": "Java", "category": "Informática", "difficulty": "hard"},
    {"word": "VIRTUALBOX", "hint": "Virtual", "category": "Informática", "difficulty": "hard"},
    {"word": "VMWARE", "hint": "Virtualización", "category": "Informática", "difficulty": "hard"},
    {"word": "AWS", "hint": "Amazon", "category": "Informática", "difficulty": "hard"},
    {"word": "AZURE", "hint": "Microsoft", "category": "Informática", "difficulty": "hard"},
    {"word": "GCP", "hint": "Google", "category": "Informática", "difficulty": "hard"},
    {"word": "HEROKU", "hint": "PaaS", "category": "Informática", "difficulty": "hard"},
    {"word": "VERCEL", "hint": "Deploy", "category": "Informática", "difficulty": "hard"},
    {"word": "NETLIFY", "hint": "Hosting", "category": "Informática", "difficulty": "hard"},
    {"word": "CLOUDFLARE", "hint": "CDN", "category": "Informática", "difficulty": "hard"},
    {"word": "NGINX", "hint": "Servidor", "category": "Informática", "difficulty": "hard"},
    {"word": "APACHE", "hint": "Web", "category": "Informática", "difficulty": "hard"},
    {"word": "ELASTICSEARCH", "hint": "Búsqueda", "category": "Informática", "difficulty": "hard"},
    {"word": "KIBANA", "hint": "Visualización", "category": "Informática", "difficulty": "hard"},
    {"word": "JENKINS", "hint": "CI", "category": "Informática", "difficulty": "hard"},
    {"word": "TERRAFORM", "hint": "IaC", "category": "Informática", "difficulty": "hard"},
    {"word": "ANSIBLE", "hint": "Automatización", "category": "Informática", "difficulty": "hard"},
    {"word": "PROMETHEUS", "hint": "Monitoreo", "category": "Informática", "difficulty": "hard"},
    {"word": "GRAFANA", "hint": "Dashboard", "category": "Informática", "difficulty": "hard"},
    {"word": "KAFKA", "hint": "Streaming", "category": "Informática", "difficulty": "hard"},
    {"word": "RABBITMQ", "hint": "Mensajería", "category": "Informática", "difficulty": "hard"},
    {"word": "MICROSERVICIOS", "hint": "Arquitectura", "category": "Informática", "difficulty": "hard"},
    {"word": "MONOLITO", "hint": "Estructura", "category": "Informática", "difficulty": "hard"},
    {"word": "REFACTORING", "hint": "Mejora", "category": "Informática", "difficulty": "hard"},
]


async def populate_database():
    """Poblar la base de datos con palabras iniciales"""
    
    # Obtener URL de MongoDB
    mongodb_url = os.getenv("MONGODB_URL")
    if not mongodb_url:
        print("❌ Error: MONGODB_URL no encontrada en .env")
        return
    
    print("🔌 Conectando a MongoDB...")
    client = AsyncIOMotorClient(mongodb_url)
    db = client.impostor_game
    
    try:
        # Verificar conexión
        await client.admin.command('ping')
        print("✅ Conectado a MongoDB!")
        
        # Eliminar palabras existentes automáticamente
        existing_count = await db.words.count_documents({})
        
        if existing_count > 0:
            result = await db.words.delete_many({})
            print(f"🗑️  Eliminadas {result.deleted_count} palabra(s) anteriores")
        
        # Agregar palabras
        print(f"\n📝 Agregando {len(INITIAL_WORDS)} palabras a la base de datos...")
        print("⏳ Esto puede tomar unos segundos...")
        
        words_to_insert = []
        for word_data in INITIAL_WORDS:
            word_doc = {
                "word_id": str(uuid.uuid4()),
                "word": word_data["word"],
                "hint": word_data["hint"],
                "category": word_data.get("category"),
                "difficulty": word_data.get("difficulty", "medium")
            }
            words_to_insert.append(word_doc)
        
        result = await db.words.insert_many(words_to_insert)
        print(f"✅ {len(result.inserted_ids)} palabras agregadas exitosamente!")
        
        # Mostrar estadísticas
        print("\n📊 Estadísticas:")
        categories = {}
        difficulties = {}
        
        for word in words_to_insert:
            cat = word.get("category", "Sin categoría")
            diff = word.get("difficulty", "medium")
            categories[cat] = categories.get(cat, 0) + 1
            difficulties[diff] = difficulties.get(diff, 0) + 1
        
        print("\nPor categoría:")
        for cat, count in sorted(categories.items()):
            print(f"  • {cat}: {count}")
        
        print("\nPor dificultad:")
        for diff, count in sorted(difficulties.items()):
            print(f"  • {diff}: {count}")
        
        print("\n🎉 ¡Base de datos poblada exitosamente!")
        
    except Exception as e:
        print(f"❌ Error: {str(e)}")
    finally:
        client.close()
        print("\n🔌 Conexión cerrada")


if __name__ == "__main__":
    print("=" * 60)
    print("🎮 POBLADOR DE BASE DE DATOS - JUEGO DEL IMPOSTOR")
    print("=" * 60)
    asyncio.run(populate_database())
